# Generated by Django 5.2.4 on 2025-07-28 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_alter_blogpost_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="author",
            field=models.CharField(max_length=200),
        ),
    ]
